### ISSUE TITLE
Issue with closing STC positions on XTB

### ISSUE THREAD

**Issue by Rudy-Dev** [peterszombati/xapi-node#25]
Hi there, the issue only occur when trying to close STC position doesn't happen when trying to close CRT position. I'm using XTB demo account.

code:
``` ts
  try {
    await x.Socket.send
      .tradeTransaction({
        order: <POSITION_ID>,
        symbol: "RBLX.US",
        type: TYPE_FIELD.CLOSE,
        price: 0,
        volume: 1,
      })
      .then(() => {
        console.log("done");
      });
  } catch (err) {
    logError(err);
  }
```

also here is error dump:
``` ts
 JsonError
    at Socket.sendCommand (C:\Users\mazep\Desktop\Projects\TS\TradeBot\node_modules\xapi-node\build\core\Socket\SocketConnection.js:60:23)
    at C:\Users\mazep\Desktop\Projects\TS\TradeBot\node_modules\xapi-node\build\core\Socket\Socket.js:119:33
    at new Promise (<anonymous>)
    at Object.tradeTransaction (C:\Users\mazep\Desktop\Projects\TS\TradeBot\node_modules\xapi-node\build\core\Socket\Socket.js:103:24)
    at Object.g2 (C:\Users\mazep\Desktop\Projects\TS\TradeBot\dist\index.js:93:14) {
  params: {
    reason: { code: 'BE11', explain: 'Position not found (#<POSITION_ID>)' },
    transaction: {
      command: 'tradeTransaction',
      type: 'Socket',
      request: [Object],
      response: [Object],
      transactionId: '164089816808500060',
      createdAt: [Time],
      status: 3,
      transactionPromise: [Object],
      urgent: true,
      stack: 'Error\n' +
        '    at Socket.sendCommand (C:\\Users\\mazep\\Desktop\\Projects\\TS\\TradeBot\\node_modules\\xapi-node\\build\\core\\Socket\\SocketConnection.js:60:23)\n' +
        '    at C:\\Users\\mazep\\Desktop\\Projects\\TS\\TradeBot\\node_modules\\xapi-node\\build\\core\\Socket\\Socket.js:119:33\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at Object.tradeTransaction (C:\\Users\\mazep\\Desktop\\Projects\\TS\\TradeBot\\node_modules\\xapi-node\\build\\core\\Socket\\Socket.js:103:24)\n' +
        '    at Object.g2 (C:\\Users\\mazep\\Desktop\\Projects\\TS\\TradeBot\\dist\\index.js:93:14)'
    }
  }
}
```

**Comment by peterszombati** [comment]
for stocks I think you dont have to close positions you have to sell stocks for closing position but after market open I will give a try

**Comment by Rudy-Dev** [comment]
Hi, I got it working however I cannot specify orderId, It is closing the first order on the list.
This is the code that I used:
```ts
  .tradeTransaction({
        cmd: CMD_FIELD.SELL,
        customComment: null,
        expiration: 0,
        offset: 0,
        order: 0,
        price: 1,
        symbol: "LBW.PL",
        tp: 0,
        sl: 0,
        type: TYPE_FIELD.OPEN,
        volume: 500,
      })
```
